"""rename department

Revision ID: 44807c97aa9a
Revises: ebff1ec0e66c
Create Date: 2024-01-29 17:02:33.331262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44807c97aa9a'
down_revision = 'ebff1ec0e66c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
